name: Build and Push Python Image to Google Cloud Platform

on:
  push:
    branches: [ main ]

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: lesson-087
      PROJECT_ID: mlops-437407
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker Client for GCR
      run: gcloud auth configure-docker --quiet

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Push Docker Image to Google Container Registry (GCR)
      run: |
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
